### ISSUE TITLE
Rückmeldung, wenn ili File nicht utf-8 encoded ist

### ISSUE THREAD

**Issue by sjib** [claeis/ili2c#102]
Soweit ich sehe, testet ili2c im Moment nicht, ob eine Modelldatei wirklich utf-8 encoded ist - ich habe das ausprobiert und bekomme keine Meldung.

Gemäss https://github.com/claeis/ili2c/issues/14 wird aber angenommen, dass dem so ist.

Wäre es darum nicht sinnvoll, eine Fehlermeldung im Compiler auszugeben und auf utf-8 encoding zu testen?

**Comment by claeis** [comment]
Ob eine Textdatei UTF-8 codiert ist oder nicht, kann der Compiler nicht zuverlässig/sicher erkennen/testen. 

Eine Textdatei ist einfach eine Folge von Bytes (mit jedem Encoding). Das Encoding ändert nur, welches Bytes welches Zeichen ist. Mit einem falschen Encoding sieht mal also einfach auch Text (aber andere Zeichen).
