### ISSUE TITLE
fehlende Elemente in IlisMeta16

### ISSUE THREAD

**Issue by claeis** [claeis/ili2c#103]
+- fehlt

Bei SetConstraint fehlt "isBasket"

Bei ExistenceDef fehlt der Bezug zum zu prüfenden Attribut.

ExistenceConstraint = 'EXISTENCE' 'CONSTRAINT' [ Constraint-Name ':' ]
AttributePath 'REQUIRED' 'IN'
ViewableRef ':' _AttributePath_
{ 'OR' ViewableRef ':' _AttributePath_ } ';'.

    ASSOCIATION ExistenceDef =   !! 2.4
      ExistenceConstraint -<#> ExistenceConstraint;
      ExistsIn -- Class;
      Attr : MANDATORY PathOrInspFactor; !! fehlt
    END ExistenceDef;

**Comment by patrickackermann** [comment]
Bei _CompundExpr_ im Attribut _Operation_ fehlt `Plus` und `Minus`
