### ISSUE TITLE
Definition in ilismeta07 missing

### ISSUE THREAD

**Issue by vvmruder** [claeis/ili2c#109]
This is probably more a question of understanding then a actual bug.

If I try to translate the model http://models.interlis.ch/refhb23/Units-20120220.ili with ili2c 5.3.3 to ilismeta07 with:

```console
java -jar ili2c.jar -oIMD Units-20120220.ili --out Units-20120220_imd07.xml
```

I miss the `Definition` part for e.g. the `Gon` unit. For the `ABSTRACT` unit `Area` I find the following:

```xml
<Definition>
    <IlisMeta07.ModelData.CompoundExpr>
        <Operation>And</Operation>
        <SubExpressions>
            <IlisMeta07.ModelData.UnitRef>
                <Unit REF="INTERLIS.LENGTH"></Unit>
            </IlisMeta07.ModelData.UnitRef>
            <IlisMeta07.ModelData.UnitRef>
                <Unit REF="INTERLIS.LENGTH"></Unit>
            </IlisMeta07.ModelData.UnitRef>
        </SubExpressions>
    </IlisMeta07.ModelData.CompoundExpr>
</Definition>
```

Which is correct. I wonder why for the non abstract units like `Gon` the definition is not created.

Regards
C

**Comment by claeis** [comment]
em, ```IlisMeta16``` (```--IMD16```) ist das aktuelle Metamodell!?

**Comment by claeis** [comment]
Und ```Gon``` ist in ```Units``` definiert, und dafür gibt es einen Eintrag:

     <IlisMeta07.ModelData.Unit TID="Units.Gon">
