### ISSUE TITLE
ILI2.4 XSD Generierung (anpassen)

### ISSUE THREAD

**Issue by claeis** [claeis/ili2c#121]

**Comment by olivergrimm** [comment]
Wir haben den `ch.interlis.ili2c.generator.XSD24Generator` bezüglich der folgenden 2.4-Neuerungen überprüft:

- [x] MULTIGEOMETRY 
- [x] Neue Datumstypen
- [x] DefferedGenerics

Wir sehen keine weiteren Neuerungen welche auf die XSD-Generierung einen Einfluss hat.
