### ISSUE TITLE
ViewDef akzeptiert Attribut nicht, wenn es den gleichen Namen wie die Klasse hat

### ISSUE THREAD

**Issue by olivergrimm** [claeis/ili2c#135]
Eine View-Definition auf die Klasse **Dokument** des Modells Nutzungsplanung_V1_2 (https://[models.geo.admin.ch/ARE/Nutzungsplanung_V1_2.ili](https://models.geo.admin.ch/ARE/Nutzungsplanung_V1_2.ili)) wird (fälschlicherweise?) als ungültig evaluiert, wenn diese das gleich heissende Attribut '**Dokument**' enthalten soll:

```   
  VIEW v_Dokument
      PROJECTION OF Nutzungsplanung_V1_2.Rechtsvorschriften.Dokument;
    =
      Typ : Nutzungsplanung_V1_2.DokumentTyp;
      TextImWeb : Nutzungsplanung_V1_2.MultilingualUri;
      Dokument : Nutzungsplanung_V1_2.MultilingualBlob;
      AuszugIndex : -1000 .. 1000;
      Rechtsstatus : Nutzungsplanung_V1_2.RechtsStatus;
      publiziertAb : INTERLIS.XMLDate;
      publiziertBis : INTERLIS.XMLDate;

 END v_Dokument;
```

Compiler-Output:
`VIEW SH_Nutzungsplanung_V5_0_AddChecks.SH_Nutzungsplanung_V5_0_Validierung.v_Dokument can not declare several attributes bearing the same name. There is already an attribute "Dokument".`

- Eine ViewAttributes-Definition mit ALL OF führt zum gleichen Fehler
- Wenn ich im Basismodell das Attribut _Dokument_ umbenenne, dann wird der View valid evaluiert.

Kann es sein, dass die View-Interpretation kein Attribut akzeptiert, welches gleich heisst wie die Klasse?

**Comment by edigonzales** [comment]
@olivergrimm  Ich glaube du musst einen "Aliasnamen" einführen:

```
  VIEW v_Dokument
      PROJECTION OF Dok ~ Nutzungsplanung_V1_2.Rechtsvorschriften.Dokument;
    =
      ALL OF Dok;
 END v_Dokument;
```

**Comment by olivergrimm** [comment]
@edigonzales Danke!
`Info: ...compiler run done 2024-11-01 10:42:39`
