### ISSUE TITLE
Error message "Model not found" if model cannot be read (i.e. by unexpected char)

### ISSUE THREAD

**Issue by ltzur** [claeis/ili2c#27]
Wenn ein Modell vorliegt (und aus Sicht Werkzeug am richtigen Ort abgelegt ist), sollte nicht die Fehlermeldung "Model not found" erscheinen, wenn das Modell nicht gelesen werden kann (z.B. weil das Encoding nicht stimmt und der Compiler die Meldung "unexpected char" ausgibt). Besser wäre eine allgemeine Meldung wie beispielsweise "Aborted by ili2c errors" oder spezifischer wie "Aborted by unexpected char in model".

**Comment by claeis** [comment]
see also #55

**Comment by claeis** [comment]
see https://github.com/claeis/ili2c/commit/3baead0b64a8c5d4583b99aa335eb4296f702ff2
