### ISSUE TITLE
Superfluos EXTERNAL in Association

### ISSUE THREAD

**Issue by ltzur** [claeis/ili2c#28]
Das Modell https://models.geo.admin.ch/ARE/Nutzungsplanung_V1_1.ili enthält folgende Assoziation:
    ASSOCIATION Typ_Typ_Kt =
      Typ -- {0..*} Typ;
      Typ_Kt (EXTERNAL) -<> {1} Typ_Kt;
    END Typ_Typ_Kt;
Weil sich sowohl die Klasse Typ wie auch Typ_Kt im selben Topic befinden, ist EXTERNAL an dieser Stelle überflüssig. Sollte der Compiler nicht reklamieren?

**Comment by claeis** [comment]
Nein, das EXTERNAL ist nicht überflüssig, sondern notwendig. Es geht bei EXTERNAL nicht um TOPIC-übergreifende Beziehungen, sondern um Behälter-übergreifend. Im vorliegenden Fall möchte man ermöglichen, dass die Objekte Typ_Kt (die Codeliste des Kantons) in einem anderen Behälter sind, als die Objekte Typ (die Codeliste der Gemeinde); was ohne EXTERNAL nicht zulässig wäre.
