### ISSUE TITLE
test of expressions in MANDATORY CONSTRAINTs

### ISSUE THREAD

**Issue by ltzur** [claeis/ili2c#31]
Beim Auswerten von Ausdrücken mit Zeichenketten, die sich in einem externen Katalog befinden, muss der ganze "Pfad" angegeben werden, was im Moment nicht geprüft wird.

Beispiel:
MANDATORY CONSTRAINT (Bestimmungen == "R900" OR ...);

"Bestimmungen" ist ein Attribut mit der Definition: Wildruhezonen_Codelisten_V2.Codelisten.Bestimmungen_CatRef;

Der Constraint muss somit lauten:
MANDATORY CONSTAINT (Bestimmungen->Reference->Code == "R900" OR ...)

**Comment by claeis** [comment]
duplicate of #17
