### ISSUE TITLE
INTERLIS 2.4: Test of MULTICOORD has failed

### ISSUE THREAD

**Issue by ltzur** [claeis/ili2c#38]
Die Verwendung von MULTICOORD in einem Modell für INTERLIS 2.4 führt zu einer Fehlermeldung und einer anschliessenden NullPointerException (Modell siehe unten).

[CHBase_Part1_GEOMETRY_20190415_DRAFT.zip](https://github.com/claeis/ili2c/files/3138826/CHBase_Part1_GEOMETRY_20190415_DRAFT.zip)

**Comment by claeis** [comment]
siehe Syntaxregel CoordinateType. Man kann nicht schreiben `MULTICOORD Coord2;`
