### ISSUE TITLE
Missing MANDATORY in extended referencies

### ISSUE THREAD

**Issue by ltzur** [claeis/ili2c#40]
Im Modell "Modell_Codelisten_V1" muss das Attribut REFERENCE TO (Zeilen 36, 41 und 46) auf MANDATORY gesetzt werden und der Compiler eine entsprechende Fehlermeldung ausgeben.

Korrekt wäre somit:
Reference (EXTENDED) : MANDATORY REFERENCE TO (EXTERNAL) Bestimmungen_Catalogue;

Das Modell findet sich hier [Modell_V1.zip](https://github.com/claeis/ili2c/files/3362711/Modell_V1.zip).

**Comment by claeis** [comment]
der Compiler muss das als Fehler melden, weil das Basis-Attribut Reference in MandatoryCatalogueReference schon MANDATORY ist (und somit in einer Erweiterung nicht zu optional abgeschwächt werden kann)

**Comment by signedav** [comment]
Dies ist nicht nur bei References so, sondern auch bei einfachen TEXT Attributen:
```
    CLASS Haus =
      Name: TEXT;
      Material : MANDATORY TEXT;
    END Haus;

    CLASS Huette EXTENDS Haus=
      Material (EXTENDED): TEXT*99;
    END Huette;
```
Ich denke, hier wär auch ein MANDATORY angebracht in `Huette.Material`.

**Comment by claeis** [comment]
> Dies ist nicht nur bei References so, sondern auch bei einfachen TEXT Attributen

Ja
