### ISSUE TITLE
Wrong VERSION in ilimodels.xml created with mkilimodelsxml

### ISSUE THREAD

**Issue by mizehnder** [claeis/ili2c#60]
Bei fehlerhaften Modellen, z.B. aus dem Ordner \obsolete, wird die VERSION mit der Funktion `MakeIliModelsXml` nicht korrekt aus den Modellen gelesen. Es wird das publishingDate des Modells in die Version im ilimodels.xml geschrieben. Weitere Angaben wie precursorVersion, Titel und shortDescription werden ignoriert. 
Nach erfolgter Modellkorrektur werden die Angaben korrekt ausgelesen.

**Comment by claeis** [comment]
Wenn die ili-Datei durch den Compiler nicht mehr gelesen werden kann (z.B. wegen einer genaueren/strengeren Prüfung), kann die VERSION Angabe desswegen nicht mehr aus dem ili ausgelesen werden. Das sollte ja aber nur bei der initialen Erstellung des ilimodels.xml ein Problem sein. Bei einer Nachführung (Update) müssen nur neue (und darum valide) ili-Dateien gelesen werden.
