### ISSUE TITLE
Make DEFAULT_ILIDIRS available as env var

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2c#64]
Nicht sicher, ob das wirklich schlau ist, weil man nicht jede Option jetzt als ENV-Variable haben will/kann. Aber so könnte man organisationsweit und immer gleich und ohne in jeder Software eigene Optionen setzen zu müssen die Repositories, die einem interessieren, verwenden. Oder auf einen organisationsweiten (sprich im gleichen Netzwerk) Cache zeigen.

**Comment by claeis** [comment]
Das funktioniert nicht, weil z.B. ili2db per Default zuerst in der DB nach den Modellen sucht/suchen muss (man will ja beim import/export genau das gleiche Modell, das man für den Schemaimport benutzt hat).

**Comment by claeis** [comment]
Das kann schon funktionieren, wenn man es schafft, DEFAULT_ILIDIRS so zu setzen, dass es für alle Tools funktioniert (und die Tools (z.B. ilivalidator) unbekannte Platzhalter (z.B. ```%ILI_FROM_DB```) stillschweigend ignorieren).

**Comment by schmandr** [comment]
OK, ich sehe, dass das nicht ganz simpel ist. Vielen Dank aber auf jeden Fall für deine Überlegungen.

Übrigens noch zum Hintergrund dieser Idee: Wir versprechen uns davon, dass wir unsere GRETL-Jobs etwas beschleunigen und Netzwerktraffic reduzieren können. Denn im Moment durchsucht GRETL jeweils (fast) alle Kantons-Modellrepositories, weil die Solothurner Modelle in der alphabetischen Reihenfolge erst gegen den Schluss drankommen. Um nun umzustellen auf `%ILI_FROM_DB;%XTF_DIR;https://geo.so.ch/models;https://models.interlis.ch/;%JAR_DIR`, müssen wir das bei jedem GRETL-Task setzen.
Für den Moment werden wir das aber wohl mal so umsetzen. (Wir werden den String irgendwie in einer Variablen verfügbar machen.)

**Comment by schmandr** [comment]
Die Unterschiede zwischen ili2db und ilivalidator gehen noch weiter: bei ili2db heisst es z.B. `%XTF_DIR`, bei ilivalidator `%ITF_DIR`. Aber eigentlich müssen diese beiden Werkzeuge/Bibliotheken gar nicht dieselbe Umgebungsvariable verwenden. Es liegt aus meiner Sicht schon drin, eine Umgebungsvariable für ili2db und eine separate für ilivalidator zu setzen.

In diesem Sinne haben wir es nun auch bei uns gelöst:
Jeder GRETL-Job hat die Variablen
`ili2dbModeldir=%ILI_FROM_DB;%XTF_DIR;https://geo.so.ch/models/;%JAR_DIR`
und
`ilivalidatorModeldir=%ITF_DIR;https://geo.so.ch/models/;%JAR_DIR`
zur Verfügung.
Nun müssen wir einfach bei allen ili2pg-Tasks die Option
`modeldir = ili2dbModeldir`
und bei allen ilivalidator-Tasks die Option
`modeldir = ilivalidatorModeldir`
setzen. Das funktioniert so, aber schade ist eben, dass man dies nun bei jedem Task setzen muss.

Langer Rede kurzer Sinn: Wir müssen aus meiner Sicht den Fokus gar nicht darauf legen, dass alle ili-Tools dieselbe Umgebungsvariable nutzen können. Sondern dass die Option `modeldir` überhaupt per Umgebungsvariable konfiguriert werden kann. Und wenn jedes Tool eben eine eigene Umgebungsvariable benötigt, ist das nicht so schlimm.

**Comment by claeis** [comment]
Die (neue, einheitliche) Umgebungsvariable würde aber in jedem Fall durch die bereits vorhandenen Kommandozeilenoptionen übersteuert, richtig?

**Comment by schmandr** [comment]
> Die (neue, einheitliche) Umgebungsvariable würde aber in jedem Fall durch die bereits vorhandenen Kommandozeilenoptionen übersteuert, richtig?

Ja, auf jeden Fall.

**Comment by schmandr** [comment]
> Das kann schon funktionieren, wenn man es schafft, DEFAULT_ILIDIRS so zu setzen, dass es für alle Tools funktioniert (und die Tools (z.B. ilivalidator) unbekannte Platzhalter (z.B. `%ILI_FROM_DB`) stillschweigend ignorieren).

Meine neusten empirischen Untersuchungen haben ergeben:
* _ili2pg_ ignoriert stillschweigend diejenigen Platzhalter, die es nicht kennt
* _ilivalidator_ meldet bei den Platzhaltern, die er nicht kennt, eine Warnung und ignoriert sie, z.B.
  ```
  Info: lookup model <DM01AVSO24LV95> 1.0 in repository <%ILI_FROM_DB/>
  Warning: Folder /home/gradle/project/%ILI_FROM_DB doesn't exist; ignored
  Info: lookup model <DM01AVSO24LV95> 1.0 in repository <%XTF_DIR/>
  Warning: Folder /home/gradle/project/%XTF_DIR doesn't exist; ignored
  ```
Die Werkzeuge verhalten sich also zwar nicht genau gleich, aber es ist eigentlich bereits gut so, wie es ist. D.h. meine obige Aussage
> Wir müssen aus meiner Sicht den Fokus gar nicht darauf legen, dass alle ili-Tools dieselbe Umgebungsvariable nutzen können.

relativiert sich insofern, dass das eigentlich bereits der Fall ist. Für unseren Use Case benötigen wir also doch nur _eine_ Variable, und diese kann von beiden Werkzeugen benutzt werden. Ihr Wert lautet dann
`%ILI_FROM_DB;%XTF_DIR;%ITF_DIR;https://geo.so.ch/models/;%JAR_DIR`

Dann fehlt also wirklich nur noch die Möglichkeit, `modeldir` überhaupt per Umgebungsvariable setzen zu können.

**Comment by schmandr** [comment]
:+1: Sehr schön!
