### ISSUE TITLE
IMD output expects defined Language

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2c#65]
Falls ein Modell keinen Language-Namen aufweist, erscheint eine Exception:

```
INTERLIS 2.3;
CONTRACTED MODEL SO_FunctionsExt
  AT "mailto:stefan.ziegler@bd.so.ch" VERSION "2019-12-04" =
```
```
  java.lang.IllegalArgumentException: illegal value null for Language
    illegal value null for Language
```

https://github.com/claeis/ili2c/blob/master/src/main/java/ch/interlis/ili2c/generator/ImdGenerator.java#L102

**Comment by Robinini** [comment]
Auch festgestellt für Interlis 1 ili Dateien. Gibt es ein Workaround - ich kenne Java leider nicht?
