### ISSUE TITLE
ILI2.4 support

### ISSUE THREAD

**Issue by claeis** [claeis/ili2c#68]
- [x] Syntaxregeln
- [x] Konsistenzbedingungen (Constraints) mit Namen
- [x] #89
- [x] #90
- [x] #72
- [x] #73
- [x] #74
- [x] #91
- [x] #121
- [x] #104
- [ ] UML Generierung (anpassen)
- [ ] ILI Generierung (anpassen)
- [x] #86
- [x] #95
- [x] #116
- [x] #117
- [x] #118 
- [x] #120

**Comment by beistehen** [comment]
@olivergrimm @Philippluca
Sind die INTERLIS Standardfunktionen wie `INTERLIS.objectCount()` bereits implementiert in ILI2.4 oder gehören diese auch auf die Liste? Ich erhielt komische Fehlermeldungen und sah, dass es unter [test/java/ch/interlis/ili2c/Interlis24](https://github.com/claeis/ili2c/tree/master/test/java/ch/interlis/ili2c/Interlis24) noch gar keine Tests dazu gibt.

**Comment by olivergrimm** [comment]
@beistehen Wir habens nicht auf der Task-List und ein kurzer Test mit ili2c 5.3.2 hat m.E. bestätigt, dass der 2.4-Support bereits besteht:
`SET CONSTRAINT INTERLIS.objectCount(Abkuerzung) > 1;`
`MANDATORY CONSTRAINT Math_V2.add(DurchschnVerspaetung->Verspaetung, 5) > 10;
`
wird auf einem 2.4-Modell fehlerfrei kompiliert.

Beachte, dass Math und Text für INTERLIS2.4 als Math_V2 bzw. Text_V2 bereitstehen. Nützt Dir das?

**Comment by olivergrimm** [comment]
> @olivergrimm @Philippluca Sind die INTERLIS Standardfunktionen wie `INTERLIS.objectCount()` bereits implementiert in ILI2.4 oder gehören diese auch auf die Liste? Ich erhielt komische Fehlermeldungen und sah, dass es unter [test/java/ch/interlis/ili2c/Interlis24](https://github.com/claeis/ili2c/tree/master/test/java/ch/interlis/ili2c/Interlis24) noch gar keine Tests dazu gibt.

@beistehen Wir habens nicht auf der Task-List und ein kurzer Test mit ili2c 5.3.2 hat m.E. bestätigt, dass der 2.4-Support bereits besteht:
SET CONSTRAINT INTERLIS.objectCount(Abkuerzung) > 1;
MANDATORY CONSTRAINT Math_V2.add(DurchschnVerspaetung->Verspaetung, 5) > 10; 
wird auf einem 2.4-Modell fehlerfrei kompiliert.

Beachte, dass Math und Text für INTERLIS2.4 als Math_V2 bzw. Text_V2 bereitstehen. Nützt Dir das?

**Comment by beistehen** [comment]
Danke @olivergrimm, dann ist das Problem wohl bei meiner Syntax zu suchen.

Ich versuche, transiente Attribute zu modellieren und erhalte immer die Fehlermeldung
`There is no domain "objectCount" in MODEL INTERLIS.`

Der Inhalt der Fehlermeldung ist zwar in sich korrekt, doch ich habe sie an dieser Stelle nicht erwartet. Ich werde im INTERLIS Forum ein neues Thema dazu eröffnen.

**Comment by olivergrimm** [comment]
Ergänzungen nach Besprechung mit Claude:

> Verifizieren ob das XML-Schema für ILI2.4 richtig generiert wird, und allenfalls anpassen (in ch.interlis.ili2c.generator.XSD24Generator).
