### ISSUE TITLE
--check-repo-ilis does not find "INTERLIS" model

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2c#75]
Nicht sicher, ob es der explizite Import von "INTERLIS" im Modell selber ist oder das Definieren von INTERLIS als Abhängigkeit in der _ilimodels.xml_-Datei. Jedenfalls führt das zu folgenden Meldungen: `INTERLIS: model(s) not found`. 

Der Repo-Check endet dann hier für dieses Modell: https://github.com/claeis/ili2c/blob/master/src/main/java/ch/interlis/ili2c/CheckReposIlis.java#L211

**Comment by claeis** [comment]
Das Model INTERLIS darf nicht als Abhängigkeit im ilimodels.xml aufgeführt werden. Aber die Fehlermeldung "``INTERLIS: model(s) not found``" passt nicht.
