### ISSUE TITLE
MakeIliModelsXml - Change separator to split ilidoc of model in title and shortDescription

### ISSUE THREAD

**Issue by beistehen** [claeis/ili2c#80]
Using MakeIliModelsXml tool, a ilidoc documentation of a model is split into the title (attribute _title_ in IliRepository20) and the short description (attribute _shortDescription_).

According to this code ...
https://github.com/claeis/ili2c/blob/05a94dbc96f1f0961633ff83dc050641da6b1564/src/main/java/ch/interlis/ili2c/MakeIliModelsXml2.java#L215-L229

... ilidoc is split at the first occurence of a dot "." into the two attributes.

So, when splitting a real world ilidoc like this ([source](https://models.geo.lu.ch/E1_Raumplanung/Nutzungsplanung_V310.ili))
```
/** Transfer-Geodatenmodell Nutzungsplanung Kt. LU (kantonal / kommunal)
 * Geobasisdatensatz nach Bundesrecht Nr. 73
 * --------------------------------------------------------------------------------
 * |Version No|Version Date| Who         | Modification
 * --------------------------------------------------------------------------------
 * |  V300    | 2018-06-08 | KSTEC GmbH  | Initiale Version, freigegeben am 07.06.2018
 * |  V310    | 2019-05-03 | KSTEC GmbH  | Definitive Version nach Praxistests
 * |          | 2019-05-28 | KSTEC GmbH  | Constraints zu ID und Gde_Code_C zusammengefasst
 * |          |            |             | Constraint-Info für Logfile-Ausgabe Interlis-Checker
 * |          |            |             | ergänzt -->  publizierte Version
 * |  V310    | 2022-05-30 | KSTEC GmbH  | Patch Change: Änderungshist. neu als Kommentar; 
 * |          |            |             | ModellNr. aus "VERSION" entfernt; neue Links 
 * |          |            |             | eingefügt;
 * |          |            |             | --> publizierte Version
 */
```
the _title_ with IliRepository20 is filled with
`Transfer-Geodatenmodell Nutzungsplanung Kt.`

and the _shortDescription_ starts with
`LU (kantonal / kommunal) Geobasisdatensatz nach Bundesrecht Nr. 73 ...`

I suggest to change the field separator from dot to a more unfrequent character in a title, like '#' or something else.
Any suggestions @mizehnder @edigonzales?

**Comment by claeis** [comment]
Ein anderes Zeichen finde ich keine gute Lösung, weil der Text damit im ili weniger schön/gut lesbar ist. Aber evtl. könnte man es besser machen, indem der Titel als bis zu einem Punkt-vor-einem-Zeilenumbruch interpretiert wird.

**Comment by beistehen** [comment]
> Aber evtl. könnte man es besser machen, indem der Titel als bis zu einem Punkt-vor-einem-Zeilenumbruch interpretiert wird.

Ja, das fände ich auch eine gute Lösung. Oder man lässt sogar den Punkt gerade ganz weg und schaut nur auf den ersten Zeilenumbruch?

**Comment by mizehnder** [comment]
- Wird es nur als "ilidoc" erkannt, wenn es nach "/**... " kommt?

- Nur die erste Zeile wäre auch nicht in jedem Fall sinnvoll, hier z.B. http://models.geo.admin.ch/ARE/Nutzungsplanung_V1_2.ili wäre es dann nur "Minimales Geodatenmodell"

- Kann man denn nicht die beiden Attribute mit !!@ Title= und !!@ shortDescription= angeben? Dann können alle saubere Angaben definieren.

**Comment by edigonzales** [comment]
> 
> - Kann man denn nicht die beiden Attribute mit !!@ Title= und !!@ shortDescription= angeben? Dann können alle saubere Angaben definieren.
> 
> 

Mache ich bei ili2repo auch so und finde es praktisch:

https://github.com/edigonzales/ili2repo/blob/main/app/src/main/java/ch/so/agi/ili2repo/ListModels.java#L159

**Comment by beistehen** [comment]
@mizehnder 
> * Wird es nur als "ilidoc" erkannt, wenn es nach "/**... " kommt?

Offenbar ja, dies ist aber zzt. noch nirgends dokumentiert. Siehe auch https://github.com/claeis/umleditor/issues/66 und deshalb auch https://github.com/claeis/ili2c/issues/66

> * Nur die erste Zeile wäre auch nicht in jedem Fall sinnvoll, hier z.B. http://models.geo.admin.ch/ARE/Nutzungsplanung_V1_2.ili wäre es dann nur "Minimales Geodatenmodell"

Dass dieser Mechanismus existiert (automatische Prozessierung des zu `MODEL` zugehörigen ilidoc) ist wohl nicht allgemein bekannt. Deshalb wurde vermutlich bisher nicht speziell darauf geachtet, nach Titel sowie nach Beschreibung zu unterscheiden. Dazu bräuchte es in gewissen Modellen einen patch change, falls man die automatische Erzeugung von `ilimodels.xml` in einem Repo anwenden möchte. Davor sollte aber klar sein, wie nun aufgetrennt wird.

> * Kann man denn nicht die beiden Attribute mit !!@ Title= und !!@ shortDescription= angeben? Dann können alle saubere Angaben definieren.

Ist gemäss Doku https://github.com/claeis/ili2c/blob/master/doc/ili2c.rst#interlis-metaattribute heute so nicht implementiert.

@edigonzales 
MakeIliModelsXml existiert seit mehr als 10 Jahren:
https://github.com/claeis/ili2c/blob/05a94dbc96f1f0961633ff83dc050641da6b1564/doc/CHANGELOG.txt#L537-L542
* Was hat dich dazu bewogen, mit [ili2repo](https://github.com/edigonzales/ili2repo) deine eigene Lösung zu entwickeln?
* Was sind die Vor- und Nachteile der beiden Lösungen (abgesehen vom Umgang mit @!! Title und @!! shortDescription)? MakeIliModelsXml hat z. B. auch eine _update_ Funktionalität eingebaut. Gibt es sowas bei ili2Repo auch?
* Wäre es allenfalls sinnvoll, nur eines der Tools gemeinsam weiter zu entwickeln?

**Comment by claeis** [comment]
Issues  betrf MakeIliModelsXml bitte hier https://github.com/claeis/ilimanager

**Comment by edigonzales** [comment]
@beistehen War mir damals (https://github.com/sogis/interlis-repository-creator) schon nicht bekannt und irgendwie erst jetzt klar. Ili2repo Fingerübung für Picocli und Native Images.

**Comment by edigonzales** [comment]
@beistehen Ah und ich "musste" für eigene Modelle, die gewisse Informationen nicht passend für das ilimodels.xml korrigieren. Unschön, war aber der bequemere Weg. Z.B. Meta-Attribut Issuer war falsch (keine URI oder so). Das führt zu einem nicht modellkonformen ilimodels.xml. 

Zusätzlich neu: Es gibt einen Servermodus.

Update: Für was? Welches Problem löst das?

**Comment by edigonzales** [comment]
@mizehnder Ah kenne ich so ähnlich (also inkomptibler Compiler). Aber im konkreten Fall würde ich seeeeeehr viel darum geben, dass nicht nur noch Update funktioniert. ilimodels.xml als abgeleitetes Produkt sollte immer initial erstellt werden können. Ähnlich wie Caches, die 1000% auseinanderlaufen zum Master und eine Funktion brauchen, um neu befüllt zu werden.

Ein für ili2c Version B inkompatibles Modell, das mit der älteren Version A funktionieren würde, ist heute oftmals trotzdem völlig useless, weil es ein CHBase-Modell importiert, das dann aber nicht mit A kompatibel ist, weil man was geändert hat, ohne den Namen zu ändern. Das führt zudem zu Horrorszenarien beim Exportieren von Daten aus der DB.

**Comment by edigonzales** [comment]
@beistehen Ah und es prüft das XML gleich noch mit ilivalidator

**Comment by edigonzales** [comment]
@beistehen Und der Aufruf via "java -cp ili2c.jar ch.interlis.ili2c.MakeIliModelsXml2" dünkt mich nicht benutzerfreundlich.

-> Alles Dinge, die man im ilimanager besser lösen sollte.
