### ISSUE TITLE
ili2c not support https

### ISSUE THREAD

**Issue by juusechec** [claeis/ili2c#9]
When I use `https://models.geo.admin.ch/;%JAR_DIR` as `model repository` the ili model dependencies are searched in local path.

Example:

I download select the model `AGNES_V1.ili` (or any, it doesn't matter) and then I run the compiler. The output log is:

```
Info: ili2c-4.7.6-20180126
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <https://models.geo.admin.ch/>
Info: Folder /home/jorge/workspace/ili2c/build/jar/https:/models.geo.admin.ch doesn't exist; ignored
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CoordSys> 2.3 in repository <https://models.geo.admin.ch/>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CatalogueObjectTrees_V1> 2.3 in repository <https://models.geo.admin.ch/>
Info: lookup model <CatalogueObjectTrees_V1> 2.3 in repository <http://models.interlis.ch/>
GeometryCHLV95_V1, CatalogueObjectTrees_V1: model(s) not found
--- compiler run failed 2/2/18 8:14 AM
```

It is searching in `/home/jorge/workspace/ili2c/build/jar/https:/models.geo.admin.ch` and not in URI `https:\models.geo.admin.ch` as expected.

I've verify the existence of this models in file `https://models.geo.admin.ch/ilimodels.xml` and they are in location that file is specifying.

**Comment by juusechec** [comment]
This is supported since version ili2c 4.6.0 (2016-12-30) https://github.com/claeis/ili2c/blob/master/doc/CHANGELOG.txt#L58

**Comment by claeis** [comment]
```https://models.geo.admin.ch/BAZL/``` is not a repository (because it doesn't contain a ilimodels.xml nor a ilisite.xml). So it is used as a local path. Therefore the log entry ```Info: Folder C:\Users\user\Downloads\umleditor-3.6.3.7\https:\models.geo.admin.ch\BAZL```

**Comment by juusechec** [comment]
Sorry for my error, I've update the question changing the URL of repository and using other model. The problem persists.

**Comment by claeis** [comment]
Can you please add an current log?

**Comment by juusechec** [comment]
I've updated top https://github.com/claeis/ili2c/issues/9#issue-293673638

**Comment by juusechec** [comment]
Thanks, this solve the issue.
