### ISSUE TITLE
ILI2.4 generischer Koordinaten-Wertebereiche (LV03- oder LV95-Koordinaten)

### ISSUE THREAD

**Issue by claeis** [claeis/ili2c#91]

**Comment by claeis** [comment]
Test erstellen

**Comment by olivergrimm** [comment]
Die Umsetzung dieses Issues wird aktuell geklärt. Die Idee ist, die dafür im Rahmen des Update-Projekts zur verfügenden stehenden Mittel für prioritäre Issues zu verwenden.
