### ISSUE TITLE
check-repo-ilis: Prüfung von Dateien mit einem "." im Namen

### ISSUE THREAD

**Issue by KunoEpper** [claeis/ili2c#93]
**Ausgangslage**
Im Repository lag die Datei: SZ_Baugesuche_gewaessernah_V1.1.ili (beachte den Punkt zwischen den Ziffern)
Die Repository-Prüfung meldete:
`Info: TID=SZ_Baugesuche_gewaessernah_V1.1: ignored; <SZ_Baugesuche_gewaessernah_V1.1> is not a valid modelname`
Das Modell hiesst jedoch **SZ_Baugesuche_gewaessernah_V1_1** (mit einem Unterstrich zwichen den Ziffern).
Damit ist die Meldung "...not a valid modelname" falsch.

**Änderungswunsch**
Die Prüfung der Modelle soll unabhängig des Modelldateinamens erfolgen.

**Comment by beistehen** [comment]
> Damit ist die Meldung "...not a valid modelname" falsch.

Obige Meldung bezieht sich auf ilimodels.xml. Dort, im XML-Tag \<Name\> des entsprechenden Eintrags, ist der Modellname mit einem Punkt statt einen Unterstrich geschrieben, was, wie bemängelt, falsch ist.

Siehe hierzu auch die [Dokumentation zum INTERLIS Repository](https://geostandards-ch.github.io/doc_ilirepo/#_aufbau).

Aber ich gebe dir recht, auf den ersten Blick meint man, es hätte etwas mit dem eigentlichen Modell zu tun.

```
<IliRepository09.RepositoryIndex.ModelMetadata TID="SZ_Baugesuche_gewaessernah_V1.1">
  <Name>SZ_Baugesuche_gewaessernah_V1.1</Name>
  <SchemaLanguage>ili2_3</SchemaLanguage>
  <File>AFG/SZ_Baugesuche_gewaessernah_V1.1.ili</File>
  <Version>2023-05-25</Version>
  <publishingDate>2023-05-25</publishingDate>
  <Title>Baugesuche in oder an Gewässern</Title>
  <shortDescription>
    Baugesuche, die eine Veränderung eines Stand- oder Fliessgewässer nach sich ziehen
  </shortDescription>
  <Issuer>http://models.geo.sz.ch</Issuer>
  <technicalContact>mailto:geoportal@sz.ch</technicalContact>
  <md5>53AA7D4CF70155DA1E744671773D4102</md5>
</IliRepository09.RepositoryIndex.ModelMetadata>

```

**Comment by KunoEpper** [comment]
Alles klar. Danke für den Hinweis. Das habe ich falsch interpretiert.
