### ISSUE TITLE
--check-repo-ilis PrecursorVersion von übersetzten Modellen wird nicht berücksichtigt und führt zu Fehlermeldung

### ISSUE THREAD

**Issue by sjib** [claeis/ili2c#94]
Ich habe neue Versionen von Modellen im Repo ergänzt inkl. deren Übersetzung fr / it mit TRANSLATION of de  und erhalte nun Fehlermeldungen dazu beim Repo Check, weil es die neueste Version der deutschen Version nimmt anstatt die zugehörige PrecursorVersion.

`C:\Users\Stefan\AppData\Local\Temp\ioxtmp8010703497544824061\VSASDEEMINI_2020_2_f_LV95-20210929.ili:5:VSASDEEMINI_2020_LV95.VSASDEEMini does not match VSADSSMINI_2020_LV95.kga_m3s.`

analoges Problem mit der italienischen Übersetzung.

und dadurch am Schluss
`
compile failed with files: 2020/VSASDEEMINI_2020_2_f_LV95-20210929.ili, 2020/VSASDSAMINI_2020_2_i_LV95-20210929.ili
check of ili's in repositories failed`

siehe `ilimodels_VSA.log` im zip, 

In VSADSSMINI_2020_2_d_LV95-20210625.ili die zu VSASDEEMINI_2020_2_f_LV95-20210929.ili gehört, gibt es kga_m3s gar noch nicht, dies wurde erst in VSADSSMINI_2020_2_d_LV95-20230718.ili eingeführt.
Ich schliesse daraus, dass VSADSSMINI_2020_2_d_LV95-20210625.ili (fr) die neueste Version von VSADSSMINI_2020_2_d_LV95 (de) vergleicht, statt die alte Version, dh. im Vergleich das Attribut Version für die deutsche Version nicht mitberücksichtigt

```
MODEL VSASDEEMINI_2020_LV95 (fr) AT "http://www.vsa.ch/models"
  VERSION "29.09.2021" TRANSLATION OF VSADSSMINI_2020_LV95 [ "25.06.2021" ] = 
```

Das ist meiner Meinung ein Fehler, weil ich sonst nicht PrecursorVersion von übersetzten Modellen in einem Repo führen kann. Oder liege ich das falsch und habe einen Fehler in ilimodels.xml?

Kann das jemand selber lokal testen?
Mein Aufruf für lokalen Aufruf von -check-repo-ilis siehe https://github.com/claeis/ili2c/issues/81#issuecomment-1639898254

[PatchChange2020.0.1_20230720.zip](https://github.com/claeis/ili2c/files/12110847/PatchChange2020.0.1_20230720.zip)

**Comment by sjib** [comment]
Grundsätzliche Diskussion hier lanciert:
[Empfehlungen zum Aufbau von Repositories](https://interlis.discourse.group/t/empfehlungen-zum-aufbau-von-repositories/135)

**Comment by claeis** [comment]
Kein ili2c Issue
